### ISSUE TITLE
cannot add fonts

### ISSUE THREAD

**Issue by vlados** [ng-seed/angular-webpack-config#33]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```
This issue relates to https://github.com/ng-seed/universal/issues/173
So I've debugged the problem and seen that when I run in production mode it's adding one extra folder assets to the url
Example: If the files are in public/assets/assets/something.ttf it will try to load http://example.com/assets/assets/assets/something.ttf

**Comment by tanordheim** [comment]
I've worked around this by setting `publicPaths.assets` to `/assets/` instead of `assets/` in `build-config.json`, and things seem to work.

A side effect of this though, is that fonts are loaded using the URI `/assets//assets/fontawesome-webfont.af7ae505a9eed503f8b8e6982036873e.woff2` (note the double slash). It works, but it seems a bit off still :)

**Comment by vlados** [comment]
@tanordheim Look at my fork, I've made it working by few changes webpack.common
https://github.com/ng-seed/angular-webpack-config/pull/34/files
